version: '3.3'

services:
  portainer:
    networks:
      - traefik_net
    deploy:
      labels:
        - traefik.docker.network=traefik_net
        - "traefik.frontend.rule=Host:portainer.${TARGETDOMAIN}"
        - traefik.port=9000
        - traefik.protocol=http
        - traefik.backend=portainer
networks:
  traefik_net:
    external: true